theme: jekyll-theme-minimal
title: The Reddit Political Network
description: How Global Events Ripple Through Online Communities â€” An ADA Data Story
show_downloads: false
navigation:
  - title: Data Story
    url: /
  - title: GitHub Repo
    url: https://github.com/epfl-ada/ada-2025-project-papayarules
