theme: jekyll-theme-minimal
title: ADA PapayaRules Website
description: The PapayaRules website for ADA
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
