theme: jekyll-theme-minimal
title: The Reddit Event Network
description: How Global Events Ripple Through Online Communities - An ADA Data Story
show_downloads: false
navigation:
  - title: Data Story
    url: /
  - title: GitHub Repo
    url: https://github.com/epfl-ada/ada-2025-project-papayarules
